// Schema describing every section/field of the Thimadhu Vehicle Inspection Report.
// Field types: text, number, date, textarea, status (Pass/Fail/N/A), yesno, select, photo, multiphoto
const STATUS_OPTS = ["Pass", "Fail", "N/A"]

export const SECTIONS = [
  {
    title: "Buyer Information",
    fields: [
      { key: "buyerFirstName", label: "First Name", type: "text" },
      { key: "buyerLastName", label: "Last Name", type: "text" },
      { key: "buyerEmail", label: "Email", type: "text" },
    ],
  },
  {
    title: "Vehicle Information",
    fields: [
      { key: "vehicleCondition", label: "Vehicle Condition", type: "select", options: ["New", "Used"] },
      { key: "make", label: "Make", type: "text" },
      { key: "model", label: "Model", type: "text" },
      { key: "year", label: "Year", type: "number" },
      { key: "registrationNumber", label: "Registration Number", type: "text" },
      { key: "fuelType", label: "Fuel Type", type: "select", options: ["Petrol", "Diesel", "Hybrid", "Electric"] },
      { key: "color", label: "Color", type: "text" },
      { key: "mileage", label: "Mileage", type: "number" },
      { key: "vehiclePhoto", label: "Vehicle Photo", type: "photo" },
      { key: "vin", label: "Vehicle Identification Number (VIN)", type: "text" },
      { key: "engineNumber", label: "Engine Number", type: "text" },
      { key: "engineCapacity", label: "Engine Capacity", type: "text" },
      { key: "transmission", label: "Transmission", type: "text" },
      { key: "bodyType", label: "Body Type", type: "text" },
    ],
  },
  {
    title: "Vehicle Documents",
    fields: [
      { key: "vehicleBook", label: "Vehicle Book", type: "status" },
      { key: "vehicleBookPhoto", label: "Vehicle Book Photo", type: "photo" },
      { key: "vehicleBookSignature", label: "Vehicle Book Commissioners True Signature", type: "status" },
      { key: "vehicleRevenueLicense", label: "Vehicle Revenue License", type: "text" },
      { key: "vehicleInsurance", label: "Vehicle Insurance", type: "text" },
      { key: "owners", label: "Owners", type: "number" },
      { key: "numberOfSeats", label: "Number of Seats", type: "number" },
      { key: "numberOfDoors", label: "Number of Doors", type: "number" },
      { key: "vehicleFrontView", label: "Vehicle Front View", type: "photo" },
      { key: "vehicleSideViews", label: "Vehicle Side Views", type: "multiphoto" },
      { key: "vehicleRearView", label: "Vehicle Rear View", type: "photo" },
    ],
  },
  {
    title: "Vehicle History",
    fields: [
      { key: "vinMatch", label: "Vehicle Identification Number (VIN) Match", type: "status" },
      { key: "vinMatchPhoto", label: "VIN Match Photo", type: "photo" },
      { key: "scheduledMaintenance", label: "Scheduled Maintenance Performed", type: "text" },
      { key: "vehicleEmissionTest", label: "Vehicle Emission Test", type: "text" },
    ],
  },
  {
    title: "Vehicle Exterior",
    fields: [
      { key: "hasDamages", label: "Was there any damages on the vehicle?", type: "yesno" },
      { key: "damageDiagramNote", label: "Repainted/Faded/Scratches/Chips/Dents (areas)", type: "textarea" },
      { key: "damagePhotos", label: "Repainted/Faded/Scratches/Chips/Dents Photos", type: "multiphoto" },
      { key: "frontEndLights", label: "Front-End Exterior Lights", type: "status" },
      { key: "frontLightsPhotos", label: "Head Lights & Fog Lights Photos", type: "multiphoto" },
      { key: "frontLightsReason", label: "Reason (if Fail)", type: "text" },
      { key: "backEndLights", label: "Back-End Exterior Lights", type: "status" },
      { key: "tailLightsPhotos", label: "Tail Lights Photos", type: "multiphoto" },
      { key: "daytimeRunningLights", label: "Daytime Running Lights", type: "status" },
      { key: "frontSignalLights", label: "Front Signal Indicator Lights", type: "status" },
      { key: "rearSignalLights", label: "Rear Signal Indicator Lights", type: "status" },
      { key: "brakeLights", label: "Brake Lights", type: "status" },
      { key: "parkingLights", label: "Parking Lights", type: "status" },
      { key: "reverseLights", label: "Reverse Lights", type: "status" },
      { key: "hazardLights", label: "Hazard Lights", type: "status" },
      { key: "autoOnOffLighting", label: "Auto On/Off Lighting", type: "status" },
      { key: "noFloodDamage", label: "No Evidence of Flood Damage", type: "status" },
      { key: "noFireDamage", label: "No Evidence of Fire Damage", type: "status" },
      { key: "noMajorDamage", label: "No Evidence of Major Damage", type: "status" },
      { key: "noCorrosion", label: "No Evidence of Corrosion", type: "status" },
      { key: "noAcidRainDamage", label: "No Evidence of Acid Rain Damage", type: "status" },
      { key: "bodyPanelInspection", label: "Body Panel Inspection", type: "status" },
      { key: "bumperInspection", label: "Bumper Inspection", type: "status" },
      { key: "doorsInspection", label: "Doors Inspection/Alignment", type: "status" },
      { key: "hoodInspection", label: "Hood Inspection/Alignment", type: "status" },
      { key: "decklidInspection", label: "Decklid Inspection/Alignment", type: "status" },
      { key: "tailgateInspection", label: "Tailgate Inspection/Alignment", type: "status" },
      { key: "roofInspection", label: "Roof Inspection", type: "status" },
      { key: "hasPaintGauge", label: "Inspector has a gauge for measuring paint thickness?", type: "yesno" },
      { key: "hoodPaintThickness", label: "Hood Paint Thickness", type: "photo" },
      { key: "roofPaintThickness", label: "Roof Paint Thickness", type: "photo" },
      { key: "leftFrontFenderPaint", label: "Left Front Fender Paint Thickness", type: "photo" },
      { key: "leftFrontDoorPaint", label: "Left Front Door Paint Thickness", type: "photo" },
      { key: "leftRearDoorPaint", label: "Left Rear Door Paint Thickness", type: "photo" },
      { key: "leftBackFenderPaint", label: "Left Back Fender Paint Thickness", type: "photo" },
      { key: "trunkDoorPaint", label: "Trunk Door Paint Thickness", type: "photo" },
      { key: "rightFrontFenderPaint", label: "Right Front Fender Paint Thickness", type: "photo" },
      { key: "rightFrontDoorPaint", label: "Right Front Door Paint Thickness", type: "photo" },
      { key: "rightRearDoorPaint", label: "Right Rear Door Paint Thickness", type: "photo" },
      { key: "rightRearFenderPaint", label: "Right Rear Fender Paint Thickness", type: "photo" },
      { key: "hoodReleaseMechanism", label: "Hood Release Mechanisms Operate Properly", type: "status" },
      { key: "hoodHinges", label: "Hood Hinges Operate Properly", type: "status" },
      { key: "hoodPropRod", label: "Hood Prop Rod/Gas Struts Operate Properly", type: "status" },
      { key: "doorHinges", label: "Door Hinges Operate Properly", type: "status" },
      { key: "trunkHinges", label: "Trunk/Tailgate Hinges/Gas Struts Operate Properly", type: "status" },
      { key: "powerLiftgate", label: "Power Liftgate Operation", type: "status" },
      { key: "trimInspection", label: "Trim Inspection", type: "status" },
      { key: "roofRackInspection", label: "Roof Rack Inspection", type: "status" },
      { key: "sideGlassInspection", label: "Side Glass Inspection", type: "status" },
      { key: "rearWindowGlassInspection", label: "Rear Window/Tailgate Glass Inspection", type: "status" },
      { key: "rearWindowGlassPhoto", label: "Rear Window/Tailgate Glass Photo", type: "photo" },
      { key: "frontWiperCondition", label: "Front Wiper Blade Condition", type: "status" },
      { key: "rearWiperCondition", label: "Rear Wiper Blade Condition", type: "status" },
      { key: "outsideFoldingMirror", label: "Outside Folding Mirror Inspection", type: "status" },
    ],
  },
  {
    title: "Vehicle Interior",
    fields: [
      { key: "dashboardPanel", label: "Dashboard Panel", type: "status" },
      { key: "dashboardPhoto", label: "Dashboard & Steering Wheel Photo", type: "photo" },
      { key: "airConditioning", label: "Air Conditioning System", type: "status" },
      { key: "acVent", label: "AC Vent", type: "status" },
      { key: "centerConsoleArea", label: "Center Console Area", type: "status" },
      { key: "radioMultimedia", label: "Radio, Multimedia Player & Speakers", type: "status" },
      { key: "antenna", label: "Antenna", type: "status" },
      { key: "tiltSteeringWheel", label: "Tilt Steering Wheel", type: "status" },
      { key: "steeringColumnLock", label: "Steering Column Lock", type: "status" },
      { key: "horn", label: "Horn", type: "status" },
      { key: "windshieldWipers", label: "Windshield Wipers Operate Properly", type: "status" },
      { key: "rearWindowWipers", label: "Rear Window Wipers Operate Properly", type: "status" },
      { key: "rearWindowWipersReason", label: "Reason (if Fail)", type: "text" },
      { key: "washersOperate", label: "Washers Operate Properly", type: "status" },
      { key: "interiorCourtesyLights", label: "Interior Courtesy, Dome and Map Lights", type: "status" },
      { key: "outsideRearviewMirrors", label: "Outside Rearview Mirrors", type: "status" },
      { key: "autoDimmingMirror", label: "Auto-Dimming Rearview Mirror", type: "status" },
      { key: "blindSpotSystem", label: "Blind Spot Information System", type: "status" },
      { key: "doorBeadings", label: "Door Beadings", type: "status" },
      { key: "powerOutletsUsb", label: "Power Outlets & USB ports", type: "status" },
      { key: "gloveBox", label: "Glove Box", type: "status" },
      { key: "centerArmrest", label: "Center Armrest", type: "status" },
      { key: "sunVisors", label: "Sun Visors, Vanity Mirror and Light", type: "status" },
      { key: "interiorOdorFree", label: "Interior Odor-Free", type: "status" },
      { key: "carpets", label: "Carpets", type: "status" },
      { key: "carpetsPhotos", label: "Carpets Photos", type: "multiphoto" },
      { key: "carpetsReason", label: "Reason (if Fail)", type: "text" },
      { key: "floorMats", label: "Floor Mats", type: "status" },
      { key: "doorTrimPanels", label: "Door Trim and Door Panels", type: "status" },
      { key: "headliner", label: "Headliner", type: "status" },
      { key: "seatUpholstery", label: "Seat Upholstery", type: "status" },
      { key: "seatUpholsteryPhotos", label: "Seat Upholstery Photos", type: "multiphoto" },
      { key: "roofUpholstery", label: "Roof Upholstery", type: "status" },
      { key: "seatHeadRestraint", label: "Seat and Head Restraint Adjustment", type: "status" },
      { key: "foldingSeats", label: "Folding Seats", type: "status" },
      { key: "heatedSeats", label: "Heated Seats", type: "status" },
      { key: "childSafetySeats", label: "Integrated Child Safety Seats", type: "status" },
      { key: "sunroof", label: "Sunroof", type: "status" },
      { key: "doorHandlesRelease", label: "Door Handles and Release Mechanisms", type: "status" },
      { key: "pushButtonStart", label: "Push-Button Start System", type: "status" },
      { key: "windowControls", label: "Window Controls", type: "status" },
      { key: "windowControlsPhoto", label: "Window Controls Photo", type: "photo" },
      { key: "windowControlsReason", label: "Reason (if Fail)", type: "text" },
      { key: "remoteDecklidRelease", label: "Remote Decklid Release", type: "status" },
      { key: "fuelFillerDoorRelease", label: "Fuel Filler Door Release", type: "status" },
      { key: "luggageCompartmentCarpet", label: "Luggage Compartment Carpet", type: "status" },
      { key: "luggageCompartmentPhotos", label: "Luggage Compartment Photos", type: "multiphoto" },
      { key: "luggageTrimCargoNet", label: "Luggage Compartment Trim and Cargo Net", type: "status" },
      { key: "luggageAreaLight", label: "Luggage Compartment Area Light", type: "status" },
      { key: "vehicleJackToolKit", label: "Vehicle Jack and Tool Kit", type: "status" },
      { key: "vehicleJackPhoto", label: "Vehicle Jack and Tool Kit Photo", type: "photo" },
      { key: "spareTireInspection", label: "Spare Tire Size/Type and Sidewall Inspection", type: "status" },
      { key: "spareTirePhoto", label: "Spare Tire Photo", type: "photo" },
      { key: "spareTireTreadDepth", label: "Spare Tire Tread Depth/Air Pressure Inspection", type: "status" },
      { key: "tireInflatorKit", label: "Tire Inflator Kit", type: "status" },
      { key: "emergencyTrunkRelease", label: "Emergency Trunk-Lid Release", type: "status" },
    ],
  },
  {
    title: "Safety & Security",
    fields: [
      { key: "collisionWarning", label: "Collision Warning", type: "status" },
      { key: "airbags", label: "Airbags", type: "status" },
      { key: "safetySeatBelts", label: "Safety Seat Belts", type: "status" },
      { key: "vehicleKey", label: "Vehicle Key", type: "status" },
      { key: "remoteEntrySystem", label: "Remote Entry System", type: "status" },
      { key: "doorLocks", label: "Door Locks", type: "status" },
      { key: "childSafetyLocks", label: "Child Safety Locks", type: "status" },
      { key: "tirePressureMonitoring", label: "Tire Pressure Monitoring", type: "status" },
      { key: "alarmTheftDeterrent", label: "Alarm/Theft-Deterrent System", type: "status" },
    ],
  },
  {
    title: "Vehicle Diagnostics (Scanning)",
    fields: [
      { key: "diagnosticSelfTest", label: "Perform Self Test For All Continuous Memory Diagnostic Trouble Code", type: "status" },
      { key: "diagnosticDate", label: "Diagnostic Date/Time", type: "text" },
      { key: "scanPhotos", label: "Vehicle Scanning Photos", type: "multiphoto" },
      { key: "scanReportFile", label: "Scan Report PDF", type: "photo" },
      { key: "errorCodesReasons", label: "Error Codes & Reasons", type: "text" },
    ],
  },
  {
    title: "Hybrid & Electric",
    fields: [
      { key: "hybridBattery", label: "Hybrid Battery", type: "status" },
      { key: "hybridBatteryReportFile", label: "Hybrid Battery Live Data Report PDF", type: "photo" },
      { key: "stateOfCharge", label: "State of Charge/ Usable Capacity", type: "status" },
      { key: "stateOfChargeValue", label: "Value (%)", type: "text" },
      { key: "hybridInfoDisplay", label: "Hybrid Entertainment and Information Display", type: "status" },
      { key: "electricPowerOutlet", label: "Electric Power Outlet", type: "status" },
    ],
  },
  {
    title: "Underhood",
    fields: [
      { key: "engineCondition", label: "Engine Condition", type: "status" },
      { key: "engineBayPhoto", label: "Engine Bay Photo", type: "photo" },
      { key: "engineCombustionLeakTest", label: "Engine Combustion Leak Test", type: "status" },
      { key: "engineOilCondition", label: "Engine Oil Condition", type: "status" },
      { key: "engineOilPhoto", label: "Engine Oil Dipstick Photo", type: "photo" },
      { key: "engineOilReason", label: "Reason (if Fail)", type: "text" },
      { key: "engineSludgeCoolant", label: "Engine Sludge, Water or Engine Coolant in Oil", type: "status" },
      { key: "exhaustSmoke", label: "Exhaust Smoke", type: "status" },
      { key: "chassisLube", label: "Chassis Lube", type: "status" },
      { key: "coolant", label: "Coolant", type: "status" },
      { key: "brakeFluidCondition", label: "Brake Fluid Condition", type: "status" },
      { key: "brakeFluidPhoto", label: "Brake Fluid Tester Photo", type: "photo" },
      { key: "airFilter", label: "Air Filter", type: "status" },
      { key: "cabinFilter", label: "Cabin Filter", type: "text" },
      { key: "autoTransmissionFluid", label: "Automatic Transmission Fluid", type: "status" },
      { key: "powerSteeringFluid", label: "Power Steering Fluid", type: "status" },
      { key: "washerFluid", label: "Washer Fluid", type: "status" },
      { key: "fluidLeaks", label: "Fluid Leaks", type: "status" },
      { key: "hosesLinesFittings", label: "Hoses, Lines and Fittings", type: "status" },
      { key: "belts", label: "Belts", type: "status" },
      { key: "wiring", label: "Wiring", type: "status" },
      { key: "oilPressure", label: "Oil Pressure", type: "status" },
      { key: "timingBelt", label: "Timing Belt", type: "status" },
      { key: "engineMounts", label: "Engine Mounts", type: "status" },
      { key: "radiator", label: "Radiator", type: "status" },
      { key: "radiatorCapPressureTest", label: "Pressure-Test Radiator Cap and Radiator", type: "status" },
      { key: "coolingFans", label: "Cooling Fans, Clutches and Motors", type: "status" },
      { key: "coolingFansReason", label: "Reason (if Fail)", type: "text" },
      { key: "coolantRecoveryTank", label: "Coolant Recovery Tank", type: "status" },
      { key: "fuelPumpNoise", label: "Fuel Pump Noise/Pressure Normal", type: "status" },
      { key: "starterMotorOperation", label: "Starter Motor Operation", type: "status" },
      { key: "ignitionSystem", label: "Ignition System", type: "status" },
      { key: "batteryCondition", label: "12V Battery Condition", type: "status" },
      { key: "batteryPhoto", label: "12V Battery Photo", type: "photo" },
      { key: "batteryReason", label: "Reason (if Fail)", type: "text" },
      { key: "batteryTerminals", label: "Battery Terminals", type: "status" },
      { key: "alternatorOutput", label: "Alternator Output", type: "status" },
    ],
  },
  {
    title: "Underbody",
    fields: [
      { key: "underbodyPhotos", label: "Vehicle Underbody Photos", type: "multiphoto" },
      { key: "chassisDamage", label: "Chassis Damage", type: "status" },
      { key: "fuelSupplySystem", label: "Fuel Supply System", type: "status" },
      { key: "exhaustSystemCondition", label: "Exhaust System Condition", type: "status" },
      { key: "universalJointsCv", label: "Universal Joints, CV Joints and CV Joint Boots", type: "status" },
      { key: "universalJointsPhotos", label: "Universal Joints, CV Joints and CV Joint Boots Photos", type: "multiphoto" },
      { key: "transmissionMounts", label: "Transmission Mounts (not cracked, broken or oil-soaked)", type: "status" },
      { key: "differentialDriveAxle", label: "Differential/Drive Axle", type: "status" },
      { key: "tiresMatchSize", label: "Tires Match and Correct Size", type: "status" },
      { key: "tiresPhotos", label: "Tires Photos", type: "multiphoto" },
      { key: "wheelsMatchSize", label: "Wheels Match and Correct Size", type: "status" },
      { key: "tireTreadFront", label: "Tire Tread Depth – Front Tires (L/R)", type: "status" },
      { key: "tireTreadFrontPhotos", label: "Tire Tread Depth Front Photos", type: "multiphoto" },
      { key: "tireTreadRear", label: "Tire Tread Depth – Rear Tires (L/R)", type: "status" },
      { key: "tireTreadRearPhotos", label: "Tire Tread Depth Rear Photos", type: "multiphoto" },
      { key: "tireTreadRearReason", label: "Reason (if Fail)", type: "text" },
      { key: "normalTireWear", label: "Normal Tire Wear", type: "status" },
      { key: "tirePressureFront", label: "Tire Pressure – Front Tires (L/R)", type: "status" },
      { key: "tirePressureRear", label: "Tire Pressure – Rear Tires (L/R)", type: "status" },
      { key: "wheels", label: "Wheels", type: "status" },
      { key: "alloyWheelCovers", label: "Alloy Wheel, Covers and Center Caps", type: "status" },
      { key: "rackPinionLinkage", label: "Rack-and-Pinion, Linkage and Boots", type: "status" },
      { key: "rackPinionPhoto", label: "Rack-and-Pinion Photo", type: "photo" },
      { key: "rackPinionReason", label: "Reason (if Fail)", type: "text" },
      { key: "controlArmsBushings", label: "Control Arms, Bushings and Ball Joints", type: "status" },
      { key: "tieRodsIdlerArm", label: "Tie Rods and Idler Arm", type: "status" },
      { key: "swayBarsLinks", label: "Sway Bars, Links and Bushings", type: "status" },
      { key: "springs", label: "Springs", type: "status" },
      { key: "strutsShocks", label: "Struts and Shocks", type: "status" },
      { key: "wheelAlignment", label: "Wheel Alignment", type: "status" },
      { key: "powerSteeringPump", label: "Power Steering Pump", type: "status" },
      { key: "brakePadsFront", label: "Brake Pads and Shoes – Front Brakes (L/R)", type: "status" },
      { key: "brakePadsRear", label: "Brake Pads and Shoes – Rear Brakes (L/R)", type: "status" },
      { key: "brakeLinesHoses", label: "Brake Lines, Hoses and Fittings", type: "status" },
      { key: "parkingBrake", label: "Parking Brake", type: "status" },
      { key: "masterCylinderBooster", label: "Master Cylinder and Booster", type: "status" },
      { key: "absModule", label: "ABS Module", type: "status" },
    ],
  },
  {
    title: "Road Test",
    fields: [
      { key: "dashboardWarningLights", label: "Dashboard Warning Lights Go On/Off", type: "status" },
      { key: "engineStartsProperly", label: "Engine Starts Properly", type: "status" },
      { key: "engineTemperature", label: "Engine Temperature", type: "status" },
      { key: "engineAcceleratesSmoothly", label: "Engine Accelerates Smoothly", type: "status" },
      { key: "engineNoiseNormal", label: "Engine Noise Normal (High/ Low Speeds)", type: "status" },
      { key: "vehicleStability", label: "Vehicle Stability", type: "status" },
      { key: "transmissionOperation", label: "Auto/ Manual Transmission Operation", type: "status" },
      { key: "reverseCameraOperates", label: "Reverse Camera Operates Properly", type: "status" },
      { key: "handParkingBrakesOperates", label: "Hand/ Parking Brakes Operates Properly", type: "status" },
      { key: "clutchOperates", label: "Clutch Operates Properly", type: "status" },
      { key: "steersNormally", label: "Steers Normally (Response, Centering, Free Play)", type: "status" },
      { key: "wipersWashers", label: "Wipers & Washers", type: "status" },
      { key: "suspensionShocksOperate", label: "Suspension/Shocks Operate Properly", type: "status" },
      { key: "suspensionReason", label: "Reason (if Fail)", type: "text" },
      { key: "brakesOperateProperly", label: "Brakes Operate Properly", type: "status" },
      { key: "gaugesOperateProperly", label: "Gauges Operate Properly", type: "status" },
      { key: "noAbnormalWindNoise", label: "No Abnormal Wind Noise", type: "status" },
    ],
  },
  {
    title: "Summary",
    fields: [
      { key: "technicianComments", label: "Technicians Comments", type: "textarea" },
      { key: "damagesMissingComponents", label: "Damages & Missing Components", type: "textarea" },
      { key: "damagesPhotos", label: "Damages & Missing Components Photos", type: "multiphoto" },
      { key: "recommendations", label: "Recommendations", type: "textarea" },
      { key: "marketPriceValuation", label: "Market Price Valuation", type: "text" },
    ],
  },
  {
    title: "Sign Off",
    fields: [
      { key: "inspectedBy", label: "Inspected by", type: "text" },
      { key: "signatureName", label: "Signature (type full name)", type: "text" },
      { key: "signOffDate", label: "Date", type: "date" },
    ],
  },
]

export const STATUS_OPTIONS = STATUS_OPTS

export function buildInitialData() {
  const data = {}
  SECTIONS.forEach((section) => {
    section.fields.forEach((field) => {
      if (field.type === "multiphoto") data[field.key] = []
      else data[field.key] = ""
    })
  })
  return data
}
